<?php

return [
    [
        'key' => 'field_65e855f654d0f',
        'label' => 'Transformation Rh',
        'name' => 'transformation_rh',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '20%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f01',
        'label' => 'Transformation Pt',
        'name' => 'transformation_pt',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '20%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f02',
        'label' => 'Transformation Ru',
        'name' => 'transformation_ru',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '20%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f03',
        'label' => 'Transformation Au',
        'name' => 'transformation_au',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '20%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f04',
        'label' => 'Transformation Ag',
        'name' => 'transformation_ag',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '20%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f05',
        'label' => 'Transformation Pd',
        'name' => 'transformation_pd',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f06',
        'label' => 'Transformation Bad',
        'name' => 'transformation_bad',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f07',
        'label' => 'Rhodium',
        'name' => 'transformation_rhodium',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '33%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f08',
        'label' => 'Platin',
        'name' => 'transformation_platin',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '33%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f09',
        'label' => 'Ruthenium',
        'name' => 'transformation_ruthenium',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '33%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f010',
        'label' => 'Gold',
        'name' => 'transformation_gold',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '33%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f011',
        'label' => 'Silber',
        'name' => 'transformation_silber',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '33%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
    [
        'key' => 'field_65e855f654d0f012',
        'label' => 'Palladium',
        'name' => 'transformation_palladium',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '33%',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 0,
        'min' => 0,
        'max' => '',
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ],
];